/** Declaration file generated by dts-gen */

declare const errorSwitch: {
    ACCOUNT_ALREADY_EXISTS: {
        description: string;
        name: string;
        type: string;
    };
    APPLE_FAILED: {
        description: string;
        name: string;
        type: string;
    };
    DATA_INVALID: {
        description: string;
        name: string;
        type: string;
    };
    DEPENDENCY_FAILURE: {
        description: string;
        name: string;
        type: string;
    };
    EMAIL_INVALID: {
        description: string;
        name: string;
        type: string;
    };
    EMAIL_OTP_NOT_SENT: {
        description: string;
        name: string;
        type: string;
    };
    EMAIL_SEND_FAILED: {
        description: string;
        name: string;
        type: string;
    };
    ENTRY_CREATE_FAILED: {
        description: string;
        name: string;
        type: string;
    };
    ENTRY_DELETE_FAILED: {
        description: string;
        name: string;
        type: string;
    };
    ENTRY_UPDATE_FAILED: {
        description: string;
        name: string;
        type: string;
    };
    EXPIRED_TOKEN: {
        description: string;
        name: string;
        type: string;
    };
    FACEBOOK_FAILED: {
        description: string;
        name: string;
        type: string;
    };
    FILE_UPLOAD_FAILED: {
        description: string;
        name: string;
        type: string;
    };
    GITHUB_FAILED: {
        description: string;
        name: string;
        type: string;
    };
    GLOBAL_ERROR: {
        description: string;
        name: string;
        type: string;
    };
    GOOGLE_FAILED: {
        description: string;
        name: string;
        type: string;
    };
    INVALID_TOKEN: {
        description: string;
        name: string;
        type: string;
    };
    IP_INVALID: {
        description: string;
        name: string;
        type: string;
    };
    KNOWN_DATABASE_ERROR: {
        description: string;
        name: string;
        type: string;
    };
    LOGIN_FAILED: {
        description: string;
        name: string;
        type: string;
    };
    NO_PERMISSION: {
        description: string;
        name: string;
        type: string;
    };
    OTP_CONFIRM_LIMIT: {
        description: string;
        name: string;
        type: string;
    };
    OTP_INCORRECT: {
        description: string;
        name: string;
        type: string;
    };
    OTP_NOT_SENT: {
        description: string;
        name: string;
        type: string;
    };
    OTP_REQUEST_LIMIT: {
        description: string;
        name: string;
        type: string;
    };
    PASSWORD_WEAK: {
        description: string;
        name: string;
        type: string;
    };
    PAYMENT_AUTHORIZATION_FAILED: {
        description: string;
        name: string;
        type: string;
    };
    PAYMENT_CAPTURE_FAILED: {
        description: string;
        name: string;
        type: string;
    };
    PAYMENT_CREATE_FAILED: {
        description: string;
        name: string;
        type: string;
    };
    PAYMENT_REFUND_FAILED: {
        description: string;
        name: string;
        type: string;
    };
    PAYMENT_SIGNATURE_MISMATCH: {
        description: string;
        name: string;
        type: string;
    };
    PHONE_INVALID: {
        description: string;
        name: string;
        type: string;
    };
    RATE_EXCEEDED: {
        description: string;
        name: string;
        type: string;
    };
    TEMPORARY_TOKEN_INVALID: {
        description: string;
        name: string;
        type: string;
    };
    TWITTER_FAILED: {
        description: string;
        name: string;
        type: string;
    };
    UNKNOWN_DATABASE_ERROR: {
        description: string;
        name: string;
        type: string;
    };
    USER_BLOCKED: {
        description: string;
        name: string;
        type: string;
    };
};

export = errorSwitch